[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.45.2",
    "litellm>=1.61.6",
    "smolagents[gardio,gradio]>=1.9.2",
]
